package core.common;

public enum ModuleType {
	CDHIT_JOB, QPMS9_JOB, BOWTIE2_JOB, TOMTOM_JOB, 
	SEQ_LOGO_JOB, PMS_CONSENSUS_JOB, NUCFREQ_JOB, 
	EXTERNAL_COMMAND, SAMTOOLS_JOB, INPUT_READER, 
	INPUT_TEST, TEST_TRANSFER, TEST_OUTPUT,
	UNDEFINED 
}
